export interface City {
  code: string;
  name: string;
  stateCode: string;
  countryCode: string;
}

export const CITIES: City[] = [
  { code: "NYC", name: "New York City", stateCode: "NY", countryCode: "US" },
  { code: "LA", name: "Los Angeles", stateCode: "CA", countryCode: "US" },
  { code: "CHI", name: "Chicago", stateCode: "IL", countryCode: "US" },
  { code: "HOU", name: "Houston", stateCode: "TX", countryCode: "US" },
  { code: "PHX", name: "Phoenix", stateCode: "AZ", countryCode: "US" },
  { code: "PHI", name: "Philadelphia", stateCode: "PA", countryCode: "US" },
  { code: "SA", name: "San Antonio", stateCode: "TX", countryCode: "US" },
  { code: "SD", name: "San Diego", stateCode: "CA", countryCode: "US" },
  { code: "DAL", name: "Dallas", stateCode: "TX", countryCode: "US" },
  { code: "SJ", name: "San Jose", stateCode: "CA", countryCode: "US" },
  { code: "AUS", name: "Austin", stateCode: "TX", countryCode: "US" },
  { code: "JAX", name: "Jacksonville", stateCode: "FL", countryCode: "US" },
  { code: "FW", name: "Fort Worth", stateCode: "TX", countryCode: "US" },
  { code: "COL", name: "Columbus", stateCode: "OH", countryCode: "US" },
  { code: "CHA", name: "Charlotte", stateCode: "NC", countryCode: "US" },
  { code: "SF", name: "San Francisco", stateCode: "CA", countryCode: "US" },
  { code: "IND", name: "Indianapolis", stateCode: "IN", countryCode: "US" },
  { code: "SEA", name: "Seattle", stateCode: "WA", countryCode: "US" },
  { code: "DEN", name: "Denver", stateCode: "CO", countryCode: "US" },
  { code: "WAS", name: "Washington", stateCode: "DC", countryCode: "US" },
  { code: "BOS", name: "Boston", stateCode: "MA", countryCode: "US" },
  { code: "ELP", name: "El Paso", stateCode: "TX", countryCode: "US" },
  { code: "NASH", name: "Nashville", stateCode: "TN", countryCode: "US" },
  { code: "DET", name: "Detroit", stateCode: "MI", countryCode: "US" },
  { code: "OKC", name: "Oklahoma City", stateCode: "OK", countryCode: "US" },
  { code: "POR", name: "Portland", stateCode: "OR", countryCode: "US" },
  { code: "LV", name: "Las Vegas", stateCode: "NV", countryCode: "US" },
  { code: "MEM", name: "Memphis", stateCode: "TN", countryCode: "US" },
  { code: "LOU", name: "Louisville", stateCode: "KY", countryCode: "US" },
  { code: "BAL", name: "Baltimore", stateCode: "MD", countryCode: "US" },
  { code: "MIL", name: "Milwaukee", stateCode: "WI", countryCode: "US" },
  { code: "ALB", name: "Albuquerque", stateCode: "NM", countryCode: "US" },
  { code: "TUC", name: "Tucson", stateCode: "AZ", countryCode: "US" },
  { code: "FRES", name: "Fresno", stateCode: "CA", countryCode: "US" },
  { code: "SAC", name: "Sacramento", stateCode: "CA", countryCode: "US" },
  { code: "MES", name: "Mesa", stateCode: "AZ", countryCode: "US" },
  { code: "KC", name: "Kansas City", stateCode: "MO", countryCode: "US" },
  { code: "ATL", name: "Atlanta", stateCode: "GA", countryCode: "US" },
  { code: "LON", name: "Long Beach", stateCode: "CA", countryCode: "US" },
  {
    code: "COL2",
    name: "Colorado Springs",
    stateCode: "CO",
    countryCode: "US",
  },
  { code: "RAL", name: "Raleigh", stateCode: "NC", countryCode: "US" },
  { code: "MIA", name: "Miami", stateCode: "FL", countryCode: "US" },
  { code: "VIR", name: "Virginia Beach", stateCode: "VA", countryCode: "US" },
  { code: "OMA", name: "Omaha", stateCode: "NE", countryCode: "US" },
  { code: "OAK", name: "Oakland", stateCode: "CA", countryCode: "US" },
  { code: "MIN", name: "Minneapolis", stateCode: "MN", countryCode: "US" },
  { code: "TUL", name: "Tulsa", stateCode: "OK", countryCode: "US" },
  { code: "ARL", name: "Arlington", stateCode: "TX", countryCode: "US" },
  { code: "TAM", name: "Tampa", stateCode: "FL", countryCode: "US" },
  { code: "NO", name: "New Orleans", stateCode: "LA", countryCode: "US" },

  { code: "TOR", name: "Toronto", stateCode: "ON", countryCode: "CA" },
  { code: "MON", name: "Montreal", stateCode: "QC", countryCode: "CA" },
  { code: "VAN", name: "Vancouver", stateCode: "BC", countryCode: "CA" },
  { code: "CAL", name: "Calgary", stateCode: "AB", countryCode: "CA" },
  { code: "EDM", name: "Edmonton", stateCode: "AB", countryCode: "CA" },
  { code: "OTT", name: "Ottawa", stateCode: "ON", countryCode: "CA" },
  { code: "WIN", name: "Winnipeg", stateCode: "MB", countryCode: "CA" },
  { code: "QUE", name: "Quebec City", stateCode: "QC", countryCode: "CA" },
  { code: "HAM", name: "Hamilton", stateCode: "ON", countryCode: "CA" },
  { code: "KIT", name: "Kitchener", stateCode: "ON", countryCode: "CA" },
  { code: "LON2", name: "London", stateCode: "ON", countryCode: "CA" },
  { code: "VIC", name: "Victoria", stateCode: "BC", countryCode: "CA" },
  { code: "HAL", name: "Halifax", stateCode: "NS", countryCode: "CA" },
  { code: "OSA", name: "Oshawa", stateCode: "ON", countryCode: "CA" },
  { code: "WIN2", name: "Windsor", stateCode: "ON", countryCode: "CA" },
  { code: "SAS", name: "Saskatoon", stateCode: "SK", countryCode: "CA" },
  { code: "REG", name: "Regina", stateCode: "SK", countryCode: "CA" },
  { code: "SHER", name: "Sherbrooke", stateCode: "QC", countryCode: "CA" },
  { code: "STJ", name: "St. John's", stateCode: "NL", countryCode: "CA" },
  { code: "BAR", name: "Barrie", stateCode: "ON", countryCode: "CA" },

  { code: "LON3", name: "London", stateCode: "ENG", countryCode: "GB" },
  { code: "BIR", name: "Birmingham", stateCode: "ENG", countryCode: "GB" },
  { code: "MAN", name: "Manchester", stateCode: "ENG", countryCode: "GB" },
  { code: "GLA", name: "Glasgow", stateCode: "SCT", countryCode: "GB" },
  { code: "LIV", name: "Liverpool", stateCode: "ENG", countryCode: "GB" },
  { code: "LEE", name: "Leeds", stateCode: "ENG", countryCode: "GB" },
  { code: "SHE", name: "Sheffield", stateCode: "ENG", countryCode: "GB" },
  { code: "EDI", name: "Edinburgh", stateCode: "SCT", countryCode: "GB" },
  { code: "BRI", name: "Bristol", stateCode: "ENG", countryCode: "GB" },
  { code: "CAR", name: "Cardiff", stateCode: "WLS", countryCode: "GB" },
  { code: "BEL", name: "Belfast", stateCode: "NIR", countryCode: "GB" },
  { code: "LEI", name: "Leicester", stateCode: "ENG", countryCode: "GB" },
  { code: "COV", name: "Coventry", stateCode: "ENG", countryCode: "GB" },
  { code: "HUL", name: "Hull", stateCode: "ENG", countryCode: "GB" },
  { code: "BRA", name: "Bradford", stateCode: "ENG", countryCode: "GB" },
  { code: "STO", name: "Stoke-on-Trent", stateCode: "ENG", countryCode: "GB" },
  { code: "WOL", name: "Wolverhampton", stateCode: "ENG", countryCode: "GB" },
  { code: "NOT", name: "Nottingham", stateCode: "ENG", countryCode: "GB" },
  { code: "PLY", name: "Plymouth", stateCode: "ENG", countryCode: "GB" },
  { code: "SOU", name: "Southampton", stateCode: "ENG", countryCode: "GB" },

  { code: "SYD", name: "Sydney", stateCode: "NSW", countryCode: "AU" },
  { code: "MEL", name: "Melbourne", stateCode: "VIC", countryCode: "AU" },
  { code: "BRI2", name: "Brisbane", stateCode: "QLD", countryCode: "AU" },
  { code: "PER", name: "Perth", stateCode: "WA", countryCode: "AU" },
  { code: "ADE", name: "Adelaide", stateCode: "SA", countryCode: "AU" },
  { code: "GOL", name: "Gold Coast", stateCode: "QLD", countryCode: "AU" },
  { code: "NEW", name: "Newcastle", stateCode: "NSW", countryCode: "AU" },
  { code: "CAN", name: "Canberra", stateCode: "ACT", countryCode: "AU" },
  { code: "SUN", name: "Sunshine Coast", stateCode: "QLD", countryCode: "AU" },
  { code: "WOL2", name: "Wollongong", stateCode: "NSW", countryCode: "AU" },
  { code: "HOB", name: "Hobart", stateCode: "TAS", countryCode: "AU" },
  { code: "GEE", name: "Geelong", stateCode: "VIC", countryCode: "AU" },
  { code: "TWN", name: "Townsville", stateCode: "QLD", countryCode: "AU" },
  { code: "CAI", name: "Cairns", stateCode: "QLD", countryCode: "AU" },
  { code: "DAR", name: "Darwin", stateCode: "NT", countryCode: "AU" },
  { code: "TOO", name: "Toowoomba", stateCode: "QLD", countryCode: "AU" },
  { code: "BAL2", name: "Ballarat", stateCode: "VIC", countryCode: "AU" },
  { code: "BEN", name: "Bendigo", stateCode: "VIC", countryCode: "AU" },
  { code: "ALB2", name: "Albury", stateCode: "NSW", countryCode: "AU" },
  { code: "LAU", name: "Launceston", stateCode: "TAS", countryCode: "AU" },

  { code: "BER", name: "Berlin", stateCode: "BE", countryCode: "DE" },
  { code: "HAM2", name: "Hamburg", stateCode: "HH", countryCode: "DE" },
  { code: "MUN", name: "Munich", stateCode: "BY", countryCode: "DE" },
  { code: "COL3", name: "Cologne", stateCode: "NW", countryCode: "DE" },
  { code: "FRA", name: "Frankfurt", stateCode: "HE", countryCode: "DE" },
  { code: "STU", name: "Stuttgart", stateCode: "BW", countryCode: "DE" },
  { code: "DUS", name: "Düsseldorf", stateCode: "NW", countryCode: "DE" },
  { code: "DOR", name: "Dortmund", stateCode: "NW", countryCode: "DE" },
  { code: "ESS", name: "Essen", stateCode: "NW", countryCode: "DE" },
  { code: "LEI2", name: "Leipzig", stateCode: "SN", countryCode: "DE" },
  { code: "BRE2", name: "Bremen", stateCode: "HB", countryCode: "DE" },
  { code: "DRE", name: "Dresden", stateCode: "SN", countryCode: "DE" },
  { code: "HAN", name: "Hannover", stateCode: "NI", countryCode: "DE" },
  { code: "NUR", name: "Nuremberg", stateCode: "BY", countryCode: "DE" },
  { code: "DUI", name: "Duisburg", stateCode: "NW", countryCode: "DE" },
  { code: "BOO", name: "Bochum", stateCode: "NW", countryCode: "DE" },
  { code: "WUP", name: "Wuppertal", stateCode: "NW", countryCode: "DE" },
  { code: "BIL", name: "Bielefeld", stateCode: "NW", countryCode: "DE" },
  { code: "BON", name: "Bonn", stateCode: "NW", countryCode: "DE" },
  { code: "MAN2", name: "Mannheim", stateCode: "BW", countryCode: "DE" },

  { code: "PAR", name: "Paris", stateCode: "IDF", countryCode: "FR" },
  { code: "MAR", name: "Marseille", stateCode: "PAC", countryCode: "FR" },
  { code: "LYO", name: "Lyon", stateCode: "ARA", countryCode: "FR" },
  { code: "TOU", name: "Toulouse", stateCode: "OCC", countryCode: "FR" },
  { code: "NIC", name: "Nice", stateCode: "PAC", countryCode: "FR" },
  { code: "NAN", name: "Nantes", stateCode: "PDL", countryCode: "FR" },
  { code: "STR", name: "Strasbourg", stateCode: "GES", countryCode: "FR" },
  { code: "MON2", name: "Montpellier", stateCode: "OCC", countryCode: "FR" },
  { code: "BOR", name: "Bordeaux", stateCode: "NAQ", countryCode: "FR" },
  { code: "LIL", name: "Lille", stateCode: "HDF", countryCode: "FR" },
  { code: "REN", name: "Rennes", stateCode: "BRE", countryCode: "FR" },
  { code: "REI", name: "Reims", stateCode: "GES", countryCode: "FR" },
  { code: "LEH", name: "Le Havre", stateCode: "NOR", countryCode: "FR" },
  { code: "SAI", name: "Saint-Étienne", stateCode: "ARA", countryCode: "FR" },
  { code: "TOU2", name: "Toulon", stateCode: "PAC", countryCode: "FR" },
  { code: "ANG", name: "Angers", stateCode: "PDL", countryCode: "FR" },
  { code: "GREN", name: "Grenoble", stateCode: "ARA", countryCode: "FR" },
  { code: "DIJ", name: "Dijon", stateCode: "BFC", countryCode: "FR" },
  { code: "NIM", name: "Nîmes", stateCode: "OCC", countryCode: "FR" },
  { code: "AIX", name: "Aix-en-Provence", stateCode: "PAC", countryCode: "FR" },

  { code: "ROM", name: "Rome", stateCode: "LAZ", countryCode: "IT" },
  { code: "MIL2", name: "Milan", stateCode: "LOM", countryCode: "IT" },
  { code: "NAP", name: "Naples", stateCode: "CAM", countryCode: "IT" },
  { code: "TUR", name: "Turin", stateCode: "PIE", countryCode: "IT" },
  { code: "PAL", name: "Palermo", stateCode: "SIC", countryCode: "IT" },
  { code: "GEN", name: "Genoa", stateCode: "LIG", countryCode: "IT" },
  { code: "BOL", name: "Bologna", stateCode: "EMR", countryCode: "IT" },
  { code: "FLO", name: "Florence", stateCode: "TOS", countryCode: "IT" },
  { code: "BAR2", name: "Bari", stateCode: "PUG", countryCode: "IT" },
  { code: "CAT", name: "Catania", stateCode: "SIC", countryCode: "IT" },
  { code: "VEN2", name: "Venice", stateCode: "VEN", countryCode: "IT" },
  { code: "VER", name: "Verona", stateCode: "VEN", countryCode: "IT" },
  { code: "MES2", name: "Messina", stateCode: "SIC", countryCode: "IT" },
  { code: "PAD", name: "Padua", stateCode: "VEN", countryCode: "IT" },
  { code: "TRI", name: "Trieste", stateCode: "FVG", countryCode: "IT" },
  { code: "TAR", name: "Taranto", stateCode: "PUG", countryCode: "IT" },
  { code: "BRE3", name: "Brescia", stateCode: "LOM", countryCode: "IT" },
  { code: "PRT", name: "Prato", stateCode: "TOS", countryCode: "IT" },
  { code: "PAR2", name: "Parma", stateCode: "EMR", countryCode: "IT" },
  { code: "MOD", name: "Modena", stateCode: "EMR", countryCode: "IT" },

  { code: "MAD", name: "Madrid", stateCode: "MD", countryCode: "ES" },
  { code: "BAR3", name: "Barcelona", stateCode: "CT", countryCode: "ES" },
  { code: "VAL", name: "Valencia", stateCode: "VC", countryCode: "ES" },
  { code: "SEV", name: "Seville", stateCode: "AN", countryCode: "ES" },
  { code: "ZAR", name: "Zaragoza", stateCode: "AR", countryCode: "ES" },
  { code: "MAL", name: "Málaga", stateCode: "AN", countryCode: "ES" },
  { code: "MUR", name: "Murcia", stateCode: "MC", countryCode: "ES" },
  { code: "PAL2", name: "Palma", stateCode: "IB", countryCode: "ES" },
  { code: "LAS", name: "Las Palmas", stateCode: "CN", countryCode: "ES" },
  { code: "BIL2", name: "Bilbao", stateCode: "PV", countryCode: "ES" },
  { code: "ALI", name: "Alicante", stateCode: "VC", countryCode: "ES" },
  { code: "COR", name: "Córdoba", stateCode: "AN", countryCode: "ES" },
  { code: "VALL", name: "Valladolid", stateCode: "CL", countryCode: "ES" },
  { code: "VIG", name: "Vigo", stateCode: "GA", countryCode: "ES" },
  { code: "GIR", name: "Gijón", stateCode: "AS", countryCode: "ES" },
  { code: "LOR", name: "L'Hospitalet", stateCode: "CT", countryCode: "ES" },
  { code: "VIT", name: "Vitoria-Gasteiz", stateCode: "PV", countryCode: "ES" },
  { code: "COR2", name: "A Coruña", stateCode: "GA", countryCode: "ES" },
  { code: "ELC", name: "Elche", stateCode: "VC", countryCode: "ES" },
  {
    code: "SAN",
    name: "Santa Cruz de Tenerife",
    stateCode: "CN",
    countryCode: "ES",
  },
];

export function getCities() {
  return CITIES;
}

export function getCitiesByState(stateCode: string): City[] {
  return CITIES.filter((city) => city.stateCode === stateCode);
}

export function getCitiesByCountry(countryCode: string): City[] {
  return CITIES.filter((city) => city.countryCode === countryCode);
}

export function getCityByCode(code: string): City | undefined {
  return CITIES.find((city) => city.code === code);
}

export function getCityName(code: string): string {
  const city = getCityByCode(code);
  return city ? city.name : code;
}
