export interface State {
  code: string;
  name: string;
  countryCode: string;
}

export const STATES: State[] = [
  { code: "AL", name: "Alabama", countryCode: "US" },
  { code: "AK", name: "Alaska", countryCode: "US" },
  { code: "AZ", name: "Arizona", countryCode: "US" },
  { code: "AR", name: "Arkansas", countryCode: "US" },
  { code: "CA", name: "California", countryCode: "US" },
  { code: "CO", name: "Colorado", countryCode: "US" },
  { code: "CT", name: "Connecticut", countryCode: "US" },
  { code: "DE", name: "Delaware", countryCode: "US" },
  { code: "FL", name: "Florida", countryCode: "US" },
  { code: "GA", name: "Georgia", countryCode: "US" },
  { code: "HI", name: "Hawaii", countryCode: "US" },
  { code: "ID", name: "Idaho", countryCode: "US" },
  { code: "IL", name: "Illinois", countryCode: "US" },
  { code: "IN", name: "Indiana", countryCode: "US" },
  { code: "IA", name: "Iowa", countryCode: "US" },
  { code: "KS", name: "Kansas", countryCode: "US" },
  { code: "KY", name: "Kentucky", countryCode: "US" },
  { code: "LA", name: "Louisiana", countryCode: "US" },
  { code: "ME", name: "Maine", countryCode: "US" },
  { code: "MD", name: "Maryland", countryCode: "US" },
  { code: "MA", name: "Massachusetts", countryCode: "US" },
  { code: "MI", name: "Michigan", countryCode: "US" },
  { code: "MN", name: "Minnesota", countryCode: "US" },
  { code: "MS", name: "Mississippi", countryCode: "US" },
  { code: "MO", name: "Missouri", countryCode: "US" },
  { code: "MT", name: "Montana", countryCode: "US" },
  { code: "NE", name: "Nebraska", countryCode: "US" },
  { code: "NV", name: "Nevada", countryCode: "US" },
  { code: "NH", name: "New Hampshire", countryCode: "US" },
  { code: "NJ", name: "New Jersey", countryCode: "US" },
  { code: "NM", name: "New Mexico", countryCode: "US" },
  { code: "NY", name: "New York", countryCode: "US" },
  { code: "NC", name: "North Carolina", countryCode: "US" },
  { code: "ND", name: "North Dakota", countryCode: "US" },
  { code: "OH", name: "Ohio", countryCode: "US" },
  { code: "OK", name: "Oklahoma", countryCode: "US" },
  { code: "OR", name: "Oregon", countryCode: "US" },
  { code: "PA", name: "Pennsylvania", countryCode: "US" },
  { code: "RI", name: "Rhode Island", countryCode: "US" },
  { code: "SC", name: "South Carolina", countryCode: "US" },
  { code: "SD", name: "South Dakota", countryCode: "US" },
  { code: "TN", name: "Tennessee", countryCode: "US" },
  { code: "TX", name: "Texas", countryCode: "US" },
  { code: "UT", name: "Utah", countryCode: "US" },
  { code: "VT", name: "Vermont", countryCode: "US" },
  { code: "VA", name: "Virginia", countryCode: "US" },
  { code: "WA", name: "Washington", countryCode: "US" },
  { code: "WV", name: "West Virginia", countryCode: "US" },
  { code: "WI", name: "Wisconsin", countryCode: "US" },
  { code: "WY", name: "Wyoming", countryCode: "US" },
  { code: "DC", name: "District of Columbia", countryCode: "US" },

  { code: "AB", name: "Alberta", countryCode: "CA" },
  { code: "BC", name: "British Columbia", countryCode: "CA" },
  { code: "MB", name: "Manitoba", countryCode: "CA" },
  { code: "NB", name: "New Brunswick", countryCode: "CA" },
  { code: "NL", name: "Newfoundland and Labrador", countryCode: "CA" },
  { code: "NS", name: "Nova Scotia", countryCode: "CA" },
  { code: "ON", name: "Ontario", countryCode: "CA" },
  { code: "PE", name: "Prince Edward Island", countryCode: "CA" },
  { code: "QC", name: "Quebec", countryCode: "CA" },
  { code: "SK", name: "Saskatchewan", countryCode: "CA" },
  { code: "NT", name: "Northwest Territories", countryCode: "CA" },
  { code: "NU", name: "Nunavut", countryCode: "CA" },
  { code: "YT", name: "Yukon", countryCode: "CA" },

  { code: "ENG", name: "England", countryCode: "GB" },
  { code: "SCT", name: "Scotland", countryCode: "GB" },
  { code: "WLS", name: "Wales", countryCode: "GB" },
  { code: "NIR", name: "Northern Ireland", countryCode: "GB" },

  { code: "NSW", name: "New South Wales", countryCode: "AU" },
  { code: "VIC", name: "Victoria", countryCode: "AU" },
  { code: "QLD", name: "Queensland", countryCode: "AU" },
  { code: "WA", name: "Western Australia", countryCode: "AU" },
  { code: "SA", name: "South Australia", countryCode: "AU" },
  { code: "TAS", name: "Tasmania", countryCode: "AU" },
  { code: "ACT", name: "Australian Capital Territory", countryCode: "AU" },
  { code: "NT", name: "Northern Territory", countryCode: "AU" },

  { code: "BW", name: "Baden-Württemberg", countryCode: "DE" },
  { code: "BY", name: "Bavaria", countryCode: "DE" },
  { code: "BE", name: "Berlin", countryCode: "DE" },
  { code: "BB", name: "Brandenburg", countryCode: "DE" },
  { code: "HB", name: "Bremen", countryCode: "DE" },
  { code: "HH", name: "Hamburg", countryCode: "DE" },
  { code: "HE", name: "Hesse", countryCode: "DE" },
  { code: "MV", name: "Mecklenburg-Vorpommern", countryCode: "DE" },
  { code: "NI", name: "Lower Saxony", countryCode: "DE" },
  { code: "NW", name: "North Rhine-Westphalia", countryCode: "DE" },
  { code: "RP", name: "Rhineland-Palatinate", countryCode: "DE" },
  { code: "SL", name: "Saarland", countryCode: "DE" },
  { code: "SN", name: "Saxony", countryCode: "DE" },
  { code: "ST", name: "Saxony-Anhalt", countryCode: "DE" },
  { code: "SH", name: "Schleswig-Holstein", countryCode: "DE" },
  { code: "TH", name: "Thuringia", countryCode: "DE" },

  { code: "ARA", name: "Auvergne-Rhône-Alpes", countryCode: "FR" },
  { code: "BFC", name: "Bourgogne-Franche-Comté", countryCode: "FR" },
  { code: "BRE", name: "Brittany", countryCode: "FR" },
  { code: "CVL", name: "Centre-Val de Loire", countryCode: "FR" },
  { code: "COR", name: "Corsica", countryCode: "FR" },
  { code: "GES", name: "Grand Est", countryCode: "FR" },
  { code: "HDF", name: "Hauts-de-France", countryCode: "FR" },
  { code: "IDF", name: "Île-de-France", countryCode: "FR" },
  { code: "NOR", name: "Normandy", countryCode: "FR" },
  { code: "NAQ", name: "Nouvelle-Aquitaine", countryCode: "FR" },
  { code: "OCC", name: "Occitanie", countryCode: "FR" },
  { code: "PDL", name: "Pays de la Loire", countryCode: "FR" },
  { code: "PAC", name: "Provence-Alpes-Côte d'Azur", countryCode: "FR" },

  { code: "ABR", name: "Abruzzo", countryCode: "IT" },
  { code: "BAS", name: "Basilicata", countryCode: "IT" },
  { code: "CAL", name: "Calabria", countryCode: "IT" },
  { code: "CAM", name: "Campania", countryCode: "IT" },
  { code: "EMR", name: "Emilia-Romagna", countryCode: "IT" },
  { code: "FVG", name: "Friuli-Venezia Giulia", countryCode: "IT" },
  { code: "LAZ", name: "Lazio", countryCode: "IT" },
  { code: "LIG", name: "Liguria", countryCode: "IT" },
  { code: "LOM", name: "Lombardy", countryCode: "IT" },
  { code: "MAR", name: "Marche", countryCode: "IT" },
  { code: "MOL", name: "Molise", countryCode: "IT" },
  { code: "PIE", name: "Piedmont", countryCode: "IT" },
  { code: "PUG", name: "Apulia", countryCode: "IT" },
  { code: "SAR", name: "Sardinia", countryCode: "IT" },
  { code: "SIC", name: "Sicily", countryCode: "IT" },
  { code: "TOS", name: "Tuscany", countryCode: "IT" },
  { code: "TAA", name: "Trentino-Alto Adige", countryCode: "IT" },
  { code: "UMB", name: "Umbria", countryCode: "IT" },
  { code: "VDA", name: "Aosta Valley", countryCode: "IT" },
  { code: "VEN", name: "Veneto", countryCode: "IT" },

  { code: "AN", name: "Andalusia", countryCode: "ES" },
  { code: "AR", name: "Aragon", countryCode: "ES" },
  { code: "AS", name: "Asturias", countryCode: "ES" },
  { code: "CB", name: "Cantabria", countryCode: "ES" },
  { code: "CL", name: "Castile and León", countryCode: "ES" },
  { code: "CM", name: "Castilla-La Mancha", countryCode: "ES" },
  { code: "CN", name: "Canary Islands", countryCode: "ES" },
  { code: "CT", name: "Catalonia", countryCode: "ES" },
  { code: "EX", name: "Extremadura", countryCode: "ES" },
  { code: "GA", name: "Galicia", countryCode: "ES" },
  { code: "IB", name: "Balearic Islands", countryCode: "ES" },
  { code: "MC", name: "Murcia", countryCode: "ES" },
  { code: "MD", name: "Madrid", countryCode: "ES" },
  { code: "NC", name: "Navarre", countryCode: "ES" },
  { code: "PV", name: "Basque Country", countryCode: "ES" },
  { code: "RI", name: "La Rioja", countryCode: "ES" },
  { code: "VC", name: "Valencian Community", countryCode: "ES" },
  { code: "CE", name: "Ceuta", countryCode: "ES" },
  { code: "ML", name: "Melilla", countryCode: "ES" },
];

export function getStates() {
  return STATES;
}

export function getStatesByCountry(countryCode: string): State[] {
  return STATES.filter((state) => state.countryCode === countryCode);
}

export function getStateByCode(code: string): State | undefined {
  return STATES.find((state) => state.code === code);
}

export function getStateName(code: string): string {
  const state = getStateByCode(code);
  return state ? state.name : code;
}
